Repository NVIDIA/cuCollections, pull requests merged in 2021-12, with the labels that each got.

#107 Add tests and examples for custom types
  cmake/thirdparty/get_libcudacxx.cmake
  examples/CMakeLists.txt
  examples/static_map/custom_type_example.cu
  tests/CMakeLists.txt
  tests/static_map/static_map_test.cu
  tests/static_multimap/static_multimap_test.cu
Labels: feature request, CMake, improvement

#113 [Review] Add stream support for static_map execution
  examples/static_map/static_map_example.cu
  include/cuco/detail/static_map.inl
  include/cuco/static_map.cuh
  tests/static_map/static_map_test.cu
Labels: feature request, static_map, helps: rapids

#125 Code formatting
  benchmarks/hash_table/dynamic_map_bench.cu
  benchmarks/hash_table/static_map_bench.cu
  examples/static_map/static_map_example.cu
  include/cuco/detail/dynamic_map_kernels.cuh
  include/cuco/detail/static_map.inl
  include/cuco/static_map.cuh
  tests/dynamic_map/dynamic_map_test.cu
  tests/static_map/static_map_test.cu
Labels: improvement

#126 Make sentinel getters part of public device_view API.
  include/cuco/detail/static_multimap/device_view_impl.inl
Labels: bug

#127 Fix a bug: expose public device APIs
  include/cuco/detail/probe_sequence_impl.cuh
  include/cuco/detail/static_multimap/device_view_impl.inl
  include/cuco/static_multimap.cuh
Labels: bug

#122 Add device non-shmem `pair_retrieve` functions
  include/cuco/detail/prime.hpp
  include/cuco/detail/static_multimap/device_view_impl.inl
  include/cuco/detail/static_multimap/static_multimap.inl
  include/cuco/detail/utils.cuh
  include/cuco/detail/utils.hpp
  include/cuco/static_multimap.cuh
  tests/static_multimap/static_multimap_test.cu
Labels: feature request, helps: rapids
