Repository NVIDIA/cuCollections, pull requests merged in 2022-07, with the labels that each got.

#185 [FEA] update to `rapids-cmake` v22.08
  CMakeLists.txt
Labels: type: enhancement, topic: build

#186 Update Catch2 to v2.13.9.
  tests/CMakeLists.txt
Labels: type: enhancement, topic: build

#81 Update examples and add device-side API examples
  README.md
  examples/CMakeLists.txt
  examples/static_map/device_view_example.cu
  examples/static_map/host_bulk_example.cu
  examples/static_map/static_map_example.cu
Labels: type: enhancement, topic: static_map, Needs Review

#192 Move macros to `detail/__config`
  include/cuco/detail/__config
  include/cuco/static_map.cuh
  include/cuco/static_multimap.cuh
Labels: type: enhancement, Needs Review
