Repository NVIDIA/cuCollections, pull requests merged in 2022-12, with the labels that each got.

#247 Inline sentinel namespace + add missing implicit conversion operators
  include/cuco/detail/utils.cuh
  include/cuco/sentinel.cuh
Labels: type: enhancement, Needs Review

#248 Include missing header
  include/cuco/detail/bitwise_compare.cuh
Labels: type: bug, Needs Review

#249 Remove the use of sentinel namespace
  README.md
  benchmarks/hash_table/dynamic_map_bench.cu
  benchmarks/hash_table/static_map_bench.cu
  benchmarks/hash_table/static_multimap/count_bench.cu
  benchmarks/hash_table/static_multimap/insert_bench.cu
  benchmarks/hash_table/static_multimap/optimal_retrieve_bench.cu
  benchmarks/hash_table/static_multimap/pair_retrieve_bench.cu
  benchmarks/hash_table/static_multimap/query_bench.cu
  benchmarks/hash_table/static_multimap/retrieve_bench.cu
  examples/static_map/custom_type_example.cu
  examples/static_map/device_view_example.cu
  examples/static_map/host_bulk_example.cu
  examples/static_multimap/host_bulk_example.cu
  tests/dynamic_map/unique_sequence_test.cu
  tests/static_map/custom_type_test.cu
  tests/static_map/duplicate_keys_test.cu
  tests/static_map/erase_test.cu
  tests/static_map/heterogeneous_lookup_test.cu
  tests/static_map/insert_and_find_test.cu
  tests/static_map/key_sentinel_test.cu
  tests/static_map/shared_memory_test.cu
  tests/static_map/stream_test.cu
  tests/static_map/unique_sequence_test.cu
  tests/static_multimap/custom_pair_retrieve_test.cu
  tests/static_multimap/custom_type_test.cu
  tests/static_multimap/heterogeneous_lookup_test.cu
  tests/static_multimap/insert_if_test.cu
  tests/static_multimap/multiplicity_test.cu
  tests/static_multimap/non_match_test.cu
  tests/static_multimap/pair_function_test.cu
Labels: type: enhancement, Needs Review

#252 Declare primes array inline constexpr
  include/cuco/detail/prime.hpp
Labels: type: bug, helps: rapids, P0: Must have, Needs Review

#253 Move hash function to public cuco namespace
  benchmarks/hash_table/static_multimap/optimal_retrieve_bench.cu
  include/cuco/detail/hash_functions.cuh
  include/cuco/dynamic_map.cuh
  include/cuco/hash_functions.cuh
  include/cuco/static_map.cuh
  include/cuco/static_multimap.cuh
  tests/static_map/key_sentinel_test.cu
  tests/static_map/stream_test.cu
  tests/static_multimap/custom_pair_retrieve_test.cu
  tests/static_multimap/insert_if_test.cu
  tests/static_multimap/multiplicity_test.cu
  tests/static_multimap/non_match_test.cu
  tests/static_multimap/pair_function_test.cu
Labels: type: enhancement, P1: Should have, Needs Review

#257 [REVIEW] Fix memory leak in static_map::retrieve_all
  include/cuco/detail/static_map.inl
Labels: type: bug, topic: static_map, helps: rapids, P1: Should have, Needs Review

#255 Fix prime array length
  include/cuco/detail/prime.hpp
Labels: type: bug, P1: Should have, Needs Review

#149 Erase Functionality for dynamic_map
  benchmarks/hash_table/dynamic_map_bench.cu
  benchmarks/hash_table/static_map_bench.cu
  include/cuco/detail/dynamic_map.inl
  include/cuco/detail/dynamic_map_kernels.cuh
  include/cuco/detail/static_map.inl
  include/cuco/detail/static_map_kernels.cuh
  include/cuco/dynamic_map.cuh
  include/cuco/static_map.cuh
  tests/CMakeLists.txt
  tests/dynamic_map/erase_test.cu
  tests/dynamic_map/unique_sequence_test.cu
Labels: type: enhancement, Needs Review, topic: dynamic_map

#260 Get rid of the use of sentinel namespace
  include/cuco/detail/dynamic_map.inl
  include/cuco/detail/static_map.inl
  include/cuco/detail/static_multimap/static_multimap.inl
  include/cuco/dynamic_map.cuh
  include/cuco/static_map.cuh
  include/cuco/static_multimap.cuh
Labels: type: enhancement, Needs Review
