Repository NVIDIA/cuCollections, pull requests merged in 2022-08, with the labels that each got.

#196 More descriptive names for examples
  examples/CMakeLists.txt
  examples/static_multimap/host_bulk_example.cu
Labels: type: enhancement

#199 Revert "Move macros to `detail/__config`"
  include/cuco/detail/__config
  include/cuco/static_map.cuh
  include/cuco/static_multimap.cuh
Labels: type: bug, Needs Review

#201 Move macros to `detail/__config` header … once again
  examples/CMakeLists.txt
  examples/static_map/custom_type_example.cu
  include/cuco/detail/__config
  include/cuco/detail/static_map.inl
  include/cuco/detail/static_multimap/device_view_impl.inl
  include/cuco/static_map.cuh
  include/cuco/static_multimap.cuh
  tests/CMakeLists.txt
  tests/static_map/custom_type_test.cu
  tests/static_map/heterogeneous_lookup_test.cu
  tests/static_multimap/heterogeneous_lookup_test.cu
Labels: type: enhancement, Needs Review

#203 Always download RAPIDS.cmake to ensure dependencies don't overwrite
  CMakeLists.txt
Labels: type: bug, topic: build, P0: Must have

#204 Use rapids-cmake 22.10 best practice for RAPIDS.cmake location
  CMakeLists.txt
Labels: type: enhancement, topic: build

#212 Fix typos in doc
  examples/static_map/device_view_example.cu
  include/cuco/static_map.cuh
Labels: type: docs

#214 Update README: add `static_multimap` section and godbolt live examples
  README.md
  examples/static_map/device_view_example.cu
Labels: type: docs, Needs Review

#216 cuco: Support requests to not install
  CMakeLists.txt
  cmake/thirdparty/get_libcudacxx.cmake
Labels: type: enhancement, topic: build, Needs Review

#202 Add new function insert_and_find for static_map
  include/cuco/detail/static_map.inl
  include/cuco/static_map.cuh
  tests/CMakeLists.txt
  tests/static_map/insert_and_find_test.cu
Labels: type: enhancement, topic: static_map, Needs Review

#225 Upgrade rapids-cmake
  CMakeLists.txt
  examples/static_map/device_view_example.cu
  tests/static_map/insert_and_find_test.cu
Labels: type: enhancement, topic: build, Needs Review
