Repository NVIDIA/cuCollections, pull requests merged in 2022-05, with the labels that each got.

#151 Fix a bug in `static_multimap`: add early exit for empty input
  include/cuco/detail/static_multimap/static_multimap.inl
Labels: bug, helps: rapids

#142 Erase Functionality for static_map
  benchmarks/hash_table/static_map_bench.cu
  examples/static_map/custom_type_example.cu
  examples/static_map/static_map_example.cu
  include/cuco/detail/dynamic_map.inl
  include/cuco/detail/error.hpp
  include/cuco/detail/static_map.inl
  include/cuco/detail/static_map_kernels.cuh
  include/cuco/sentinel.hpp
  include/cuco/static_map.cuh
  tests/CMakeLists.txt
  tests/static_map/custom_type_test.cu
  tests/static_map/duplicate_keys_test.cu
  tests/static_map/erase_test.cu
  tests/static_map/key_sentinel_test.cu
  tests/static_map/shared_memory_test.cu
  tests/static_map/stream_test.cu
  tests/static_map/unique_sequence_test.cu
Labels: feature request, static_map

#158 Fix Broken Links
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/submit-question.md
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
Labels: bug, documentation

#155 Make sentinel constructors constexpr
  include/cuco/sentinel.cuh
  include/cuco/static_map.cuh
Labels: improvement

#156 Fix issues in `static_map` benchmark
  benchmarks/hash_table/static_map_bench.cu
Labels: bug

#141 Make all headers self-contained
  benchmarks/hash_table/dynamic_map_bench.cu
  benchmarks/hash_table/static_multimap/count_bench.cu
  benchmarks/hash_table/static_multimap/insert_bench.cu
  benchmarks/hash_table/static_multimap/optimal_retrieve_bench.cu
  benchmarks/hash_table/static_multimap/pair_retrieve_bench.cu
  benchmarks/hash_table/static_multimap/query_bench.cu
  benchmarks/hash_table/static_multimap/retrieve_bench.cu
  benchmarks/synchronization.hpp
  examples/static_map/custom_type_example.cu
  examples/static_map/static_map_example.cu
  examples/static_multimap/static_multimap_example.cu
  include/cuco/detail/dynamic_map_kernels.cuh
  include/cuco/detail/error.hpp
  include/cuco/detail/pair.cuh
  include/cuco/detail/probe_sequence_impl.cuh
  include/cuco/detail/static_map_kernels.cuh
  include/cuco/detail/static_multimap/kernels.cuh
  include/cuco/detail/static_multimap/static_multimap.inl
  include/cuco/dynamic_map.cuh
  include/cuco/static_map.cuh
  include/cuco/static_multimap.cuh
  tests/dynamic_map/unique_sequence_test.cu
  tests/static_map/custom_type_test.cu
  tests/static_map/key_sentinel_test.cu
  tests/static_map/shared_memory_test.cu
  tests/static_map/stream_test.cu
  tests/static_map/unique_sequence_test.cu
  tests/static_multimap/custom_pair_retrieve_test.cu
  tests/static_multimap/custom_type_test.cu
  tests/static_multimap/insert_if_test.cu
  tests/static_multimap/multiplicity_test.cu
  tests/static_multimap/non_match_test.cu
  tests/static_multimap/pair_function_test.cu
Labels: type: bug

#161 Add missing Thrust includes.
  benchmarks/hash_table/dynamic_map_bench.cu
  benchmarks/hash_table/static_multimap/pair_retrieve_bench.cu
  benchmarks/reduce_by_key/reduce_by_key.cu
  examples/static_map/custom_type_example.cu
  examples/static_map/static_map_example.cu
  examples/static_multimap/static_multimap_example.cu
  include/cuco/detail/pair.cuh
  include/cuco/detail/static_map.inl
  include/cuco/detail/static_multimap/device_view_impl.inl
  include/cuco/detail/static_multimap/static_multimap.inl
  include/cuco/detail/utils.cuh
  tests/dynamic_map/unique_sequence_test.cu
  tests/static_map/custom_type_test.cu
  tests/static_map/duplicate_keys_test.cu
  tests/static_map/erase_test.cu
  tests/static_map/key_sentinel_test.cu
  tests/static_map/shared_memory_test.cu
  tests/static_map/stream_test.cu
  tests/static_map/unique_sequence_test.cu
  tests/static_multimap/custom_pair_retrieve_test.cu
  tests/static_multimap/custom_type_test.cu
  tests/static_multimap/insert_if_test.cu
  tests/static_multimap/multiplicity_test.cu
  tests/static_multimap/non_match_test.cu
  tests/static_multimap/pair_function_test.cu
Labels: type: enhancement, helps: rapids

#163 Apply sentinel namespace to other map structures
  include/cuco/detail/dynamic_map.inl
  include/cuco/detail/static_multimap/static_multimap.inl
  include/cuco/dynamic_map.cuh
  include/cuco/static_multimap.cuh
Labels: type: enhancement, Needs Review, topic: static_multimap, topic: dynamic_map

#166 Update bitwise_compare to check cuco::is_bitwise_comparable
  include/cuco/detail/bitwise_compare.cuh
Labels: type: enhancement

#168 Add missing header
  benchmarks/synchronization.hpp
Labels: type: bug

#167 Make sentinel constructors explicit
  benchmarks/hash_table/dynamic_map_bench.cu
  benchmarks/hash_table/static_multimap/count_bench.cu
  benchmarks/hash_table/static_multimap/insert_bench.cu
  benchmarks/hash_table/static_multimap/optimal_retrieve_bench.cu
  benchmarks/hash_table/static_multimap/pair_retrieve_bench.cu
  benchmarks/hash_table/static_multimap/query_bench.cu
  benchmarks/hash_table/static_multimap/retrieve_bench.cu
  examples/static_multimap/static_multimap_example.cu
  include/cuco/sentinel.cuh
  include/cuco/static_map.cuh
  include/cuco/static_multimap.cuh
  tests/dynamic_map/unique_sequence_test.cu
  tests/static_multimap/custom_pair_retrieve_test.cu
  tests/static_multimap/custom_type_test.cu
  tests/static_multimap/insert_if_test.cu
  tests/static_multimap/multiplicity_test.cu
  tests/static_multimap/non_match_test.cu
  tests/static_multimap/pair_function_test.cu
Labels: type: bug, Needs Review

#170 Add missing `#pragma once` directive
  include/cuco/detail/dynamic_map_kernels.cuh
  include/cuco/detail/static_map_kernels.cuh
  include/cuco/detail/static_multimap/kernels.cuh
Labels: type: bug
