Repository NVIDIA/cuCollections, pull requests merged in 2023-05, with the labels that each got.

#299 Clean up test code
  tests/static_multimap/custom_pair_retrieve_test.cu
  tests/static_multimap/custom_type_test.cu
  tests/static_multimap/insert_if_test.cu
  tests/static_multimap/multiplicity_test.cu
  tests/static_multimap/non_match_test.cu
  tests/static_multimap/pair_function_test.cu
  tests/utils.hpp
Labels: type: enhancement, Needs Review

#302 Bump rapids-cmake to 23.06
  CMakeLists.txt
Labels: type: enhancement, topic: build

#301 Update `static_map` size computation
  include/cuco/detail/common_kernels.cuh
  include/cuco/detail/static_map.inl
  include/cuco/detail/static_multimap/device_view_impl.inl
  include/cuco/detail/static_multimap/static_multimap.inl
  include/cuco/static_map.cuh
  include/cuco/static_multimap.cuh
  tests/static_map/erase_test.cu
Labels: type: enhancement, topic: static_map, Needs Review, topic: static_multimap

#305 Revert "Update `static_map` size computation"
  include/cuco/detail/common_kernels.cuh
  include/cuco/detail/static_map.inl
  include/cuco/detail/static_multimap/device_view_impl.inl
  include/cuco/detail/static_multimap/static_multimap.inl
  include/cuco/static_map.cuh
  include/cuco/static_multimap.cuh
  tests/static_map/erase_test.cu
Labels: helps: rapids

#306 Make size type a template parameter to get rid of narrow conversions
  include/cuco/detail/storage/aow_storage.cuh
  include/cuco/detail/storage/counter_storage.cuh
  include/cuco/detail/storage/storage_base.cuh
Labels: helps: rapids, Needs Review, topic: static_set

#307 Fix narrow conversion issues in probing iterator
  include/cuco/detail/probing_scheme_impl.inl
  tests/static_set/unique_sequence_test.cu
Labels: type: bug, helps: rapids, Needs Review

#308 Extend macros for error checking and int128 support
  README.md
  include/cuco/detail/__config
Labels: type: enhancement, Needs Review

#311 Create ops-bot.yaml
  .github/ops-bot.yaml
Labels: topic: CI

#310 New hash function alternatives
  benchmarks/CMakeLists.txt
  benchmarks/defaults.hpp
  benchmarks/hash_bench.cu
  benchmarks/hash_table/static_set/contains_bench.cu
  benchmarks/hash_table/static_set/find_bench.cu
  include/cuco/detail/hash_functions/murmurhash3.cuh
  include/cuco/detail/hash_functions/xxhash.cuh
  include/cuco/detail/probe_sequence_impl.cuh
  include/cuco/hash_functions.cuh
  tests/CMakeLists.txt
  tests/utility/hash_test.cu
Labels: helps: rapids, topic: performance, Needs Review
