Repository NVIDIA/cuCollections, pull requests merged in 2023-08, with the labels that each got.

#315 Enable fast_int functionality for dynamic extent
  include/cuco/detail/extent/extent.inl
  include/cuco/detail/open_addressing_impl.cuh
  include/cuco/detail/open_addressing_ref_impl.cuh
  include/cuco/detail/probing_scheme_impl.inl
  include/cuco/detail/storage/aow_storage.cuh
  include/cuco/detail/storage/counter_storage.cuh
  include/cuco/detail/storage/storage_base.cuh
  include/cuco/detail/utils.cuh
  include/cuco/extent.cuh
  include/cuco/static_map.cuh
  include/cuco/static_set.cuh
  include/cuco/utility/fast_int.cuh
  tests/CMakeLists.txt
  tests/static_set/capacity_test.cu
  tests/utility/extent_test.cu
Labels: type: enhancement, topic: performance, Needs Review

#344 Fix doxygen check with unsupported version.
  ci/checks/doxygen.sh
Labels: type: docs

#342 Use rapids-cmake 23.10.
  CMakeLists.txt
Labels: topic: build

#341 Fix bitwise compare alignment issues
  include/cuco/detail/bitwise_compare.cuh
Labels: type: bug

#345 Improve implememtation details in experimental data structures
  include/cuco/detail/extent/extent.inl
  include/cuco/detail/storage/aow_storage.cuh
  include/cuco/extent.cuh
  tests/CMakeLists.txt
  tests/static_set/capacity_test.cu
Labels: type: enhancement, helps: rapids

#349 Expose `aow_storage` to the public
  include/cuco/aow_storage.cuh
  include/cuco/detail/storage/aow_storage.cuh
  include/cuco/detail/storage/aow_storage.inl
  include/cuco/detail/storage/aow_storage_base.cuh
  include/cuco/detail/storage/storage.cuh
  include/cuco/detail/storage/storage_base.cuh
  include/cuco/static_map.cuh
  include/cuco/static_set.cuh
  include/cuco/storage.cuh
  tests/static_map/unique_sequence_test.cu
  tests/static_set/capacity_test.cu
  tests/static_set/insert_and_find_test.cu
  tests/static_set/retrieve_all_test.cu
  tests/static_set/unique_sequence_test.cu
  tests/utility/storage_test.cu
Labels: type: enhancement

#351 Fix alignment issue for data type larger than 16B
  include/cuco/detail/bitwise_compare.cuh
  include/cuco/detail/utils.cuh
Labels: type: bug, Needs Review

#356 Distinct code path for key equality checks in `packed_cas`
  include/cuco/detail/open_addressing_ref_impl.cuh
  include/cuco/detail/static_map/static_map_ref.inl
  include/cuco/detail/static_set/static_set_ref.inl
Labels: type: bug, topic: static_map, Needs Review

#358 Fix broken links for static_set live examples
  README.md
Labels: type: docs, topic: static_set

#360 Use `copy-pr-bot`
  .github/copy-pr-bot.yaml
  .github/ops-bot.yaml
Labels: topic: CI

#361 Add missing headers
  include/cuco/detail/open_addressing_ref_impl.cuh
  include/cuco/static_map.cuh
Labels: type: bug
