Repository NVIDIA/cuCollections, pull requests merged in 2023-09, with the labels that each got.

#353 Add `insert_or_assign` for map
  include/cuco/detail/open_addressing_ref_impl.cuh
  include/cuco/detail/static_map/kernels.cuh
  include/cuco/detail/static_map/static_map.inl
  include/cuco/detail/static_map/static_map_ref.inl
  include/cuco/operator.hpp
  include/cuco/static_map.cuh
  include/cuco/static_set.cuh
  tests/CMakeLists.txt
  tests/static_map/insert_or_assign_test.cu
Labels: type: feature request, topic: static_map, helps: rapids, Needs Review

#364 Fix typos in the documentation
  include/cuco/detail/open_addressing_impl.cuh
  include/cuco/static_map.cuh
  include/cuco/static_map_ref.cuh
  include/cuco/static_set.cuh
  include/cuco/static_set_ref.cuh
Labels: type: docs, type: improvement

#359 Clean up detail utility functions
  benchmarks/hash_bench.cu
  include/cuco/detail/common_kernels.cuh
  include/cuco/detail/extent/extent.inl
  include/cuco/detail/open_addressing_impl.cuh
  include/cuco/detail/prime.hpp
  include/cuco/detail/static_map/kernels.cuh
  include/cuco/detail/static_map/static_map.inl
  include/cuco/detail/static_multimap/static_multimap.inl
  include/cuco/detail/static_set/kernels.cuh
  include/cuco/detail/static_set/static_set.inl
  include/cuco/detail/storage/aow_storage.inl
  include/cuco/detail/storage/kernels.cuh
  include/cuco/detail/utility/cuda.cuh
  include/cuco/detail/utility/cuda.hpp
  include/cuco/detail/utility/math.hpp
  include/cuco/detail/utils.hpp
Labels: Needs Review, type: improvement

#352 Add `dynamic_bitset`
  include/cuco/detail/trie/dynamic_bitset/dynamic_bitset.cuh
  include/cuco/detail/trie/dynamic_bitset/dynamic_bitset.inl
  include/cuco/detail/trie/dynamic_bitset/kernels.cuh
  tests/CMakeLists.txt
  tests/dynamic_bitset/find_next_test.cu
  tests/dynamic_bitset/get_test.cu
  tests/dynamic_bitset/rank_test.cu
  tests/dynamic_bitset/select_test.cu
  tests/dynamic_bitset/size_test.cu
Labels: type: feature request, Needs Review

#367 Rename `insert_pair` as `insert_element` in common kernels
  include/cuco/detail/common_kernels.cuh
Labels: type: improvement

#368 Clean up ref implementations with `has_payload` flag
  include/cuco/detail/open_addressing_ref_impl.cuh
  include/cuco/detail/static_map/static_map_ref.inl
  include/cuco/detail/static_set/static_set_ref.inl
Labels: type: improvement

#346 Add device subsets example
  examples/CMakeLists.txt
  examples/static_set/device_ref_example.cu
  examples/static_set/device_subsets_example.cu
  include/cuco/aow_storage.cuh
  include/cuco/detail/extent/extent.inl
  include/cuco/detail/open_addressing_impl.cuh
  include/cuco/detail/open_addressing_ref_impl.cuh
  include/cuco/detail/static_map/static_map_ref.inl
  include/cuco/detail/static_set/static_set_ref.inl
  include/cuco/detail/storage/aow_storage.inl
  include/cuco/detail/storage/storage.cuh
  include/cuco/extent.cuh
  include/cuco/static_map_ref.cuh
  include/cuco/static_set_ref.cuh
  include/cuco/storage.cuh
Labels: type: feature request, helps: rapids, Needs Review, topic: static_set

#369 Add constructor overloads taking load factor as input
  include/cuco/detail/open_addressing_impl.cuh
  include/cuco/detail/static_map/static_map.inl
  include/cuco/detail/static_set/static_set.inl
  include/cuco/static_map.cuh
  include/cuco/static_set.cuh
  tests/CMakeLists.txt
  tests/static_map/capacity_test.cu
  tests/static_set/capacity_test.cu
Labels: type: feature request, topic: static_map, helps: rapids, Needs Review, topic: static_set
