Repository NVIDIA/cuCollections, pull requests merged in 2023-02, with the labels that each got.

#268 Improve exception handling macros
  include/cuco/detail/dynamic_map.inl
  include/cuco/detail/error.hpp
  include/cuco/detail/static_map.inl
Labels: type: enhancement, Needs Review

#269 Remove the use of sentinel namespace
  include/cuco/detail/dynamic_map.inl
  include/cuco/dynamic_map.cuh
Labels: type: enhancement

#267 Get rid of thrust::device_vector::data
  benchmarks/hash_table/static_multimap/optimal_retrieve_bench.cu
  benchmarks/hash_table/static_multimap/query_bench.cu
  benchmarks/hash_table/static_multimap/retrieve_bench.cu
  examples/static_multimap/host_bulk_example.cu
  tests/static_multimap/non_match_test.cu
Labels: type: enhancement, Needs Review

#271 New key generator to be used in benchmarks
  benchmarks/CMakeLists.txt
  benchmarks/defaults.hpp
  benchmarks/distribution.hpp
  benchmarks/hash_table/static_multimap/count_bench.cu
  benchmarks/hash_table/static_multimap/insert_bench.cu
  benchmarks/hash_table/static_multimap/optimal_retrieve_bench.cu
  benchmarks/hash_table/static_multimap/pair_retrieve_bench.cu
  benchmarks/hash_table/static_multimap/query_bench.cu
  benchmarks/hash_table/static_multimap/retrieve_bench.cu
  benchmarks/key_generator.hpp
Labels: type: enhancement, topic: performance

#270 Rewrite `static_map` benchmarks with nvbench
  .gitignore
  benchmarks/CMakeLists.txt
  benchmarks/defaults.hpp
  benchmarks/hash_table/static_map/contains_bench.cu
  benchmarks/hash_table/static_map/erase_bench.cu
  benchmarks/hash_table/static_map/find_bench.cu
  benchmarks/hash_table/static_map/insert_bench.cu
  benchmarks/hash_table/static_map_bench.cu
  benchmarks/key_generator.hpp
Labels: type: enhancement, topic: static_map
