Repository NVIDIA/cuCollections, pull requests merged in 2023-07, with the labels that each got.

#330 Fix pair implementation issues
  include/cuco/detail/pair.cuh
  include/cuco/detail/traits.hpp
Labels: helps: rapids, Needs Review

#321 Add 16-byte key-value support to `experimental::static_map`
  include/cuco/detail/open_addressing_impl.cuh
  include/cuco/detail/open_addressing_ref_impl.cuh
  include/cuco/detail/static_map/static_map_ref.inl
  include/cuco/static_map.cuh
  include/cuco/static_map_ref.cuh
  include/cuco/static_set_ref.cuh
  tests/static_map/unique_sequence_test.cu
Labels: type: enhancement, topic: static_map, Needs Review

#333 Add function to re-initialize/clear a container
  include/cuco/detail/open_addressing_impl.cuh
  include/cuco/detail/static_map/static_map.inl
  include/cuco/detail/static_set/static_set.inl
  include/cuco/static_map.cuh
  include/cuco/static_set.cuh
  tests/static_set/size_test.cu
Labels: type: enhancement, Needs Review

#327 Enable hash computation from variable length keys
  benchmarks/hash_bench.cu
  include/cuco/detail/hash_functions/murmurhash3.cuh
  include/cuco/detail/hash_functions/utils.cuh
  include/cuco/detail/hash_functions/xxhash.cuh
  tests/utility/hash_test.cu
Labels: type: enhancement

#338 Fix memory alignment issues in hash computation
  include/cuco/detail/hash_functions/utils.cuh
Labels: type: bug

#337 Add block synchronisation after reset of CG-level counters
  include/cuco/detail/static_multimap/device_view_impl.inl
  include/cuco/detail/static_multimap/kernels.cuh
Labels: type: bug, helps: rapids, Needs Review, topic: static_multimap
