Repository NVIDIA/cuCollections, pull requests merged in 2024-04, with the labels that each got.

#451 Add convenience macro for defining strong types (correctly)
  include/cuco/detail/utility/strong_type.cuh
  include/cuco/sentinel.cuh
Labels: type: bug, Needs Review

#452 Rename sentinel.cuh -> types.cuh
  include/cuco/dynamic_map.cuh
  include/cuco/operator.hpp
  include/cuco/static_map.cuh
  include/cuco/static_map_ref.cuh
  include/cuco/static_multimap.cuh
  include/cuco/static_multiset.cuh
  include/cuco/static_multiset_ref.cuh
  include/cuco/static_set.cuh
  include/cuco/static_set_ref.cuh
  include/cuco/types.cuh
  include/cuco/utility/allocator.hpp
  include/cuco/utility/cuda_thread_scope.cuh
  include/cuco/utility/traits.hpp
Labels: type: docs, Needs Review, type: improvement

#429 distinct_count_estimator aka HyperLogLog++
  README.md
  benchmarks/CMakeLists.txt
  benchmarks/distinct_count_estimator_bench.cu
  examples/CMakeLists.txt
  examples/distinct_count_estimator/device_ref_example.cu
  examples/distinct_count_estimator/host_bulk_example.cu
  include/cuco/detail/__config
  include/cuco/detail/distinct_count_estimator/distinct_count_estimator.inl
  include/cuco/detail/distinct_count_estimator/distinct_count_estimator_ref.inl
  include/cuco/detail/hyperloglog/finalizer.cuh
  include/cuco/detail/hyperloglog/hyperloglog.cuh
  include/cuco/detail/hyperloglog/hyperloglog_ref.cuh
  include/cuco/detail/hyperloglog/kernels.cuh
  include/cuco/detail/hyperloglog/tuning.cuh
  include/cuco/distinct_count_estimator.cuh
  include/cuco/distinct_count_estimator_ref.cuh
  include/cuco/types.cuh
  tests/CMakeLists.txt
  tests/distinct_count_estimator/device_ref_test.cu
  tests/distinct_count_estimator/spark_parity_test.cu
  tests/distinct_count_estimator/unique_sequence_test.cu
Labels: type: feature request, Needs Review

#453 Fix illegal memory issues in multimap benchmarks
  benchmarks/hash_table/static_multimap/query_bench.cu
  benchmarks/hash_table/static_multimap/retrieve_bench.cu
Labels: type: bug, topic: static_multimap

#456 Get rid of duplicate logic in the OA base implementations
  include/cuco/detail/open_addressing/open_addressing_impl.cuh
Labels: type: improvement

#460 Fix misuses of the `CUCO_HAS_CUDA_BARRIER` marco
  include/cuco/detail/open_addressing/open_addressing_ref_impl.cuh
  include/cuco/static_map.cuh
Labels: type: bug

#461 Bump latest CTK version to 12.4 in CI
  .devcontainer/cuda11.8-gcc11/devcontainer.json
  .devcontainer/cuda12.4-gcc12/devcontainer.json
  .devcontainer/devcontainer.json
  ci/matrix.yml
Labels: topic: CI

#459 Remove asynchronous set retrieve APIs
  include/cuco/detail/static_set/static_set.inl
  include/cuco/static_set.cuh
Labels: topic: static_set, type: improvement

#467 Add ref `with_hash_function` and `with_key_eq` APIs for set and multiset
  include/cuco/detail/probing_scheme_impl.inl
  include/cuco/detail/static_multiset/static_multiset_ref.inl
  include/cuco/detail/static_set/static_set_ref.inl
  include/cuco/probing_scheme.cuh
  include/cuco/static_multiset_ref.cuh
  include/cuco/static_set_ref.cuh
Labels: type: feature request, Needs Review, topic: static_set, topic: static_multiset
