Repository NVIDIA/cuCollections, pull requests merged in 2024-01, with the labels that each got.

#416 Get rid of unused var warnings
  tests/static_map/shared_memory_test.cu
Labels: type: improvement

#415 Move probe sequences to legacy namespace
  include/cuco/detail/probe_sequence_impl.cuh
  include/cuco/probe_sequences.cuh
  include/cuco/static_multimap.cuh
  tests/static_multimap/custom_pair_retrieve_test.cu
  tests/static_multimap/custom_type_test.cu
  tests/static_multimap/heterogeneous_lookup_test.cu
  tests/static_multimap/insert_if_test.cu
  tests/static_multimap/multiplicity_test.cu
  tests/static_multimap/non_match_test.cu
  tests/static_multimap/pair_function_test.cu
Labels: type: feature request, topic: static_multimap

#414 Move old single map to `cuco::legacy` namespace
  README.md
  include/cuco/detail/dynamic_map.inl
  include/cuco/detail/static_map.inl
  include/cuco/detail/static_map_kernels.cuh
  include/cuco/dynamic_map.cuh
  include/cuco/static_map.cuh
  tests/static_map/custom_type_test.cu
Labels: type: feature request, topic: static_map

#418 Get rid of unused var warning in set test
  tests/static_set/shared_memory_test.cu
Labels: type: improvement

#422 Mark all cuco kernels as static so they have hidden visibility
  include/cuco/detail/dynamic_map_kernels.cuh
  include/cuco/detail/open_addressing/kernels.cuh
  include/cuco/detail/static_map/kernels.cuh
  include/cuco/detail/static_map_kernels.cuh
  include/cuco/detail/static_multimap/kernels.cuh
  include/cuco/detail/static_set/kernels.cuh
  include/cuco/detail/storage/kernels.cuh
  include/cuco/detail/trie/dynamic_bitset/kernels.cuh
  include/cuco/detail/utility/cuda.cuh
Labels: type: improvement

#424 Fix set ref example: global index should take CG size into consideration
  README.md
  examples/static_set/device_ref_example.cu
Labels: type: bug, topic: static_set

#428 Fix the default erase sentinel bug in the base open addressing ctor
  include/cuco/detail/open_addressing/open_addressing_impl.cuh
  tests/static_set/insert_and_find_test.cu
  tests/static_set/retrieve_all_test.cu
Labels: type: bug, helps: rapids, topic: static_set

#431 Bump clang format version
  .pre-commit-config.yaml
  include/cuco/aow_storage.cuh
  include/cuco/detail/extent/extent.inl
  include/cuco/detail/pair/tuple_helpers.inl
  include/cuco/detail/traits.hpp
  include/cuco/dynamic_map.cuh
  include/cuco/static_map.cuh
  include/cuco/static_multimap.cuh
  include/cuco/static_set.cuh
  include/cuco/utility/key_generator.cuh
  include/cuco/utility/traits.hpp
Labels: topic: CI, type: improvement

#432 Update README.md
  README.md
Labels: type: docs, Needs Review

#434 Get rid of container dependent functors by adding `has_payload` in OA base class
  include/cuco/detail/open_addressing/functors.cuh
  include/cuco/detail/open_addressing/open_addressing_impl.cuh
  include/cuco/detail/open_addressing/open_addressing_ref_impl.cuh
  include/cuco/detail/static_map/functors.cuh
  include/cuco/detail/static_map/static_map.inl
  include/cuco/detail/static_set/functors.cuh
  include/cuco/detail/static_set/static_set.inl
Labels: Needs Review, type: improvement
