Repository NVIDIA/cuCollections, pull requests merged in 2024-12, with the labels that each got.

#648 Move kernels to their own namespaces to avoid build conflicts
  include/cuco/detail/bloom_filter/bloom_filter_impl.cuh
  include/cuco/detail/bloom_filter/kernels.cuh
  include/cuco/detail/open_addressing/functors.cuh
  include/cuco/detail/open_addressing/kernels.cuh
  include/cuco/detail/open_addressing/open_addressing_impl.cuh
  include/cuco/detail/static_map/helpers.cuh
  include/cuco/detail/static_map/kernels.cuh
  include/cuco/detail/static_map/static_map.inl
  tests/static_map/insert_or_apply_test.cu
Labels: type: bug, helps: rapids, Needs Review

#645 Add host find APIs taking custom key equality and hasher
  include/cuco/detail/static_set/static_set.inl
  include/cuco/static_set.cuh
Labels: type: feature request, helps: rapids, Needs Review, topic: static_set

#643 Add retrieve for new map/multimap
  include/cuco/detail/static_map/static_map.inl
  include/cuco/detail/static_map/static_map_ref.inl
  include/cuco/detail/static_multimap/static_multimap.inl
  include/cuco/detail/static_multimap/static_multimap_ref.inl
  include/cuco/detail/static_set/static_set.inl
  include/cuco/static_map.cuh
  include/cuco/static_multimap.cuh
  include/cuco/static_set.cuh
  tests/CMakeLists.txt
  tests/static_map/retrieve_test.cu
  tests/static_multimap/custom_pair_retrieve_test.cu
  tests/static_multimap/custom_type_test.cu
  tests/static_multimap/multiplicity_test.cu
  tests/static_multimap/non_match_test.cu
  tests/static_multimap/pair_function_test.cu
Labels: type: feature request, topic: static_map, Needs Review, topic: static_multimap

#647 Fix hash table full occupancy bug
  include/cuco/detail/open_addressing/open_addressing_ref_impl.cuh
  include/cuco/detail/static_map/static_map_ref.inl
Labels: type: bug, Needs Review

#649 Add type alias to unblock cudf build
  include/cuco/bucket_storage.cuh
Labels: helps: rapids, Needs Review

#654 Minor improvements for arrow_filter_policy
  include/cuco/bloom_filter_policies.cuh
  include/cuco/detail/bloom_filter/arrow_filter_policy.cuh
Labels: helps: rapids, type: improvement, topic: bloom_filter

#656 Replace window with bucket instead
  README.md
  examples/static_set/device_subsets_example.cu
  examples/static_set/shared_memory_example.cu
  include/cuco/bucket_storage.cuh
  include/cuco/detail/extent/extent.inl
  include/cuco/extent.cuh
  include/cuco/static_map_ref.cuh
  include/cuco/static_multimap_ref.cuh
  include/cuco/static_multiset_ref.cuh
  include/cuco/static_set_ref.cuh
  tests/static_map/insert_or_apply_test.cu
  tests/static_map/shared_memory_test.cu
  tests/static_set/shared_memory_test.cu
  tests/utility/extent_test.cu
  tests/utility/probing_scheme_test.cu
Labels: Needs Review, type: improvement
