Repository NVIDIA/cuCollections, pull requests merged in 2024-05, with the labels that each got.

#473 Ensure that `tuple_size` is defined
  include/cuco/detail/pair/traits.hpp
Labels: type: improvement

#478 Fix dynamic init warning for cuda barrier
  include/cuco/detail/open_addressing/open_addressing_ref_impl.cuh
Labels: type: bug, Needs Review

#479 Fix key equality check order
  include/cuco/detail/equal_wrapper.cuh
  include/cuco/detail/open_addressing/functors.cuh
  include/cuco/detail/open_addressing/open_addressing_ref_impl.cuh
  include/cuco/detail/static_map/static_map_ref.inl
  include/cuco/static_map.cuh
  include/cuco/static_multiset.cuh
  include/cuco/static_set.cuh
  tests/static_map/heterogeneous_lookup_test.cu
  tests/static_set/heterogeneous_lookup_test.cu
Labels: Needs Review, type: improvement

#468 Add multiset contains APIs
  include/cuco/detail/static_multiset/static_multiset.inl
  include/cuco/detail/static_multiset/static_multiset_ref.inl
  include/cuco/static_multiset.cuh
  tests/CMakeLists.txt
  tests/static_multiset/contains_test.cu
Labels: type: feature request, Needs Review, topic: static_multiset

#481 Get rid of CUDA __inline__ specifier in test functions
  tests/static_map/insert_or_assign_test.cu
  tests/static_map/unique_sequence_test.cu
  tests/static_multimap/custom_type_test.cu
  tests/static_multimap/insert_if_test.cu
  tests/static_multimap/multiplicity_test.cu
  tests/static_multimap/non_match_test.cu
  tests/static_multimap/pair_function_test.cu
  tests/static_multiset/insert_test.cu
  tests/static_set/insert_and_find_test.cu
  tests/static_set/large_input_test.cu
  tests/static_set/retrieve_all_test.cu
  tests/static_set/retrieve_test.cu
  tests/static_set/unique_sequence_test.cu
Labels: type: improvement

#482 Add ref with_operators
  README.md
  examples/static_set/device_subsets_example.cu
  examples/static_set/shared_memory_example.cu
  include/cuco/detail/static_map/static_map_ref.inl
  include/cuco/detail/static_multiset/static_multiset_ref.inl
  include/cuco/detail/static_set/static_set_ref.inl
  include/cuco/static_map_ref.cuh
  include/cuco/static_multiset_ref.cuh
  include/cuco/static_set_ref.cuh
  tests/static_map/shared_memory_test.cu
  tests/static_set/shared_memory_test.cu
Labels: type: improvement

#483 Unify host-bulk find implementations in OA base class
  include/cuco/detail/open_addressing/kernels.cuh
  include/cuco/detail/open_addressing/open_addressing_impl.cuh
  include/cuco/detail/static_map/kernels.cuh
  include/cuco/detail/static_map/static_map.inl
  include/cuco/detail/static_set/kernels.cuh
  include/cuco/detail/static_set/static_set.inl
  include/cuco/static_map.cuh
Labels: type: improvement

#470 Add multiset find APIs
  include/cuco/detail/static_multiset/static_multiset.inl
  include/cuco/detail/static_multiset/static_multiset_ref.inl
  include/cuco/static_multiset.cuh
  tests/CMakeLists.txt
  tests/static_multiset/find_test.cu
Labels: type: feature request, Needs Review, topic: static_multiset

#485 Clean up multiset find
  include/cuco/detail/static_multiset/static_multiset.inl
Labels: type: improvement, topic: static_multiset

#486 Use empty value sentinel to improve readability
  include/cuco/detail/open_addressing/open_addressing_ref_impl.cuh
Labels: type: improvement

#472 Add multiset count APIs
  benchmarks/CMakeLists.txt
  benchmarks/hash_table/static_multiset/count_bench.cu
  include/cuco/detail/equal_wrapper.cuh
  include/cuco/detail/open_addressing/kernels.cuh
  include/cuco/detail/open_addressing/open_addressing_impl.cuh
  include/cuco/detail/open_addressing/open_addressing_ref_impl.cuh
  include/cuco/detail/static_multiset/static_multiset.inl
  include/cuco/detail/static_multiset/static_multiset_ref.inl
  include/cuco/operator.hpp
  include/cuco/static_multiset.cuh
  tests/CMakeLists.txt
  tests/static_multiset/count_test.cu
Labels: type: feature request, Needs Review, topic: static_multiset

#492 Add launch bounds to kernels
  include/cuco/detail/open_addressing/kernels.cuh
  include/cuco/detail/static_map/kernels.cuh
  include/cuco/detail/static_set/kernels.cuh
Labels: topic: performance, P2: Nice to have, Needs Review

#490 Add multiset custom count APIs
  include/cuco/detail/open_addressing/kernels.cuh
  include/cuco/detail/open_addressing/open_addressing_impl.cuh
  include/cuco/detail/open_addressing/open_addressing_ref_impl.cuh
  include/cuco/detail/static_multiset/static_multiset.inl
  include/cuco/detail/static_multiset/static_multiset_ref.inl
  include/cuco/detail/utility/cuda.hpp
  include/cuco/static_multiset.cuh
  tests/CMakeLists.txt
  tests/static_multiset/custom_count_test.cu
Labels: type: feature request, helps: rapids, Needs Review, topic: static_multiset
