Repository NVIDIA/cuCollections, pull requests merged in 2024-03, with the labels that each got.

#444 Remove outdated dispatching
  include/cuco/detail/__config
  include/cuco/detail/static_multimap/device_view_impl.inl
  include/cuco/static_multimap.cuh
Labels: topic: static_multimap, type: improvement

#445 Fix flaky memcpy optimization in xxhash
  include/cuco/detail/hash_functions/xxhash.cuh
Labels: topic: performance, P1: Should have, Needs Review

#443 Add mapping table example
  README.md
  examples/CMakeLists.txt
  examples/static_set/mapping_table_example.cu
Labels: topic: static_set, type: improvement

#441 Improve erased sentinel check logic
  include/cuco/detail/equal_wrapper.cuh
  include/cuco/detail/open_addressing/open_addressing_ref_impl.cuh
  include/cuco/detail/static_map/static_map_ref.inl
Labels: Needs Review, type: improvement

#442 Add set retrieve
  include/cuco/detail/__config
  include/cuco/detail/static_set/kernels.cuh
  include/cuco/detail/static_set/static_set.inl
  include/cuco/detail/utility/cuda.cuh
  include/cuco/static_set.cuh
  tests/CMakeLists.txt
  tests/static_set/retrieve_test.cu
Labels: type: feature request, helps: rapids, Needs Review, topic: static_set

#447 Clean up pair utilities
  include/cuco/detail/open_addressing/functors.cuh
  include/cuco/detail/pair/helpers.cuh
  include/cuco/detail/pair/traits.hpp
  include/cuco/detail/utils.cuh
  include/cuco/pair.cuh
  include/cuco/utility/key_generator.cuh
Labels: Needs Review, type: improvement

#446 Clean up strong type utility
  include/cuco/detail/utility/strong_type.cuh
  include/cuco/detail/utils.cuh
  include/cuco/sentinel.cuh
  include/cuco/utility/key_generator.cuh
Labels: Needs Review, type: improvement
