Repository NVIDIA/cuCollections, pull requests merged in 2024-07, with the labels that each got.

#525 Replace cuco stream ref with `cuda::stream_ref`
  include/cuco/aow_storage.cuh
  include/cuco/cuda_stream_ref.hpp
  include/cuco/detail/cuda_stream_ref.inl
  include/cuco/detail/distinct_count_estimator/distinct_count_estimator.inl
  include/cuco/detail/distinct_count_estimator/distinct_count_estimator_ref.inl
  include/cuco/detail/hyperloglog/hyperloglog.cuh
  include/cuco/detail/hyperloglog/hyperloglog_ref.cuh
  include/cuco/detail/open_addressing/open_addressing_impl.cuh
  include/cuco/detail/static_map/static_map.inl
  include/cuco/detail/static_multiset/static_multiset.inl
  include/cuco/detail/static_set/static_set.inl
  include/cuco/detail/storage/aow_storage.inl
  include/cuco/detail/storage/counter_storage.cuh
  include/cuco/detail/trie/dynamic_bitset/dynamic_bitset.cuh
  include/cuco/detail/trie/dynamic_bitset/dynamic_bitset.inl
  include/cuco/distinct_count_estimator.cuh
  include/cuco/distinct_count_estimator_ref.cuh
  include/cuco/static_map.cuh
  include/cuco/static_multiset.cuh
  include/cuco/static_set.cuh
Labels: Needs Review, type: improvement

#517 Add host-bulk `insert_and_find` for `static_set`
  include/cuco/detail/open_addressing/kernels.cuh
  include/cuco/detail/open_addressing/open_addressing_impl.cuh
  include/cuco/detail/static_set/static_set.inl
  include/cuco/static_set.cuh
  tests/static_set/insert_and_find_test.cu
Labels: type: feature request, Needs Review, topic: static_set

#526 Get rid of custom cuda_stream_ref
  include/cuco/detail/open_addressing/open_addressing_impl.cuh
  include/cuco/detail/static_set/static_set.inl
  include/cuco/static_set.cuh
Labels: type: bug

#515 Add static_map::insert_or_apply aka reduce-by-key
  benchmarks/CMakeLists.txt
  benchmarks/hash_table/static_map/insert_or_apply_bench.cu
  include/cuco/detail/static_map/kernels.cuh
  include/cuco/detail/static_map/static_map.inl
  include/cuco/detail/static_map/static_map_ref.inl
  include/cuco/operator.hpp
  include/cuco/static_map.cuh
  include/cuco/static_map_ref.cuh
  tests/CMakeLists.txt
  tests/static_map/insert_or_apply_test.cu
Labels: type: feature request, topic: static_map, topic: performance, Needs Review

#527 Update the documentation to no longer suggest using thrust::make_pair
  README.md
  examples/static_multimap/host_bulk_example.cu
  include/cuco/dynamic_map.cuh
  include/cuco/static_map.cuh
  include/cuco/static_multimap.cuh
Labels: type: docs

#529 Fix a multimap buffer flushing bug with zip iterator
  include/cuco/detail/static_multimap/device_view_impl.inl
Labels: type: bug, Needs Review, topic: static_multimap

#533 Fix CAS dispatching bug
  include/cuco/detail/open_addressing/open_addressing_ref_impl.cuh
  include/cuco/detail/static_map.inl
Labels: type: bug, Needs Review

#535 Fix usage of `decltype` with `probing_scheme` in `.with_hash_function`
  include/cuco/detail/static_multiset/static_multiset_ref.inl
  include/cuco/detail/static_set/static_set_ref.inl
Labels: type: bug

#534 Add host-bulk insert_and_find for static_map
  include/cuco/detail/static_map/static_map.inl
  include/cuco/static_map.cuh
  tests/static_map/insert_and_find_test.cu
Labels: type: feature request, topic: static_map, Needs Review

#536 Fix broken Godbolt links
  README.md
Labels: type: docs

#531 Replace custom atomic operations with cuda atomic_ref
  include/cuco/detail/hyperloglog/hyperloglog_ref.cuh
  include/cuco/detail/open_addressing/open_addressing_ref_impl.cuh
  include/cuco/detail/static_map/static_map_ref.inl
Labels: type: improvement

#540 Fix try_reserve_shmem
  include/cuco/detail/hyperloglog/hyperloglog_ref.cuh
Labels: type: bug, P0: Must have, Needs Review

#541 Fix ABA problem in back_to_back_cas
  include/cuco/detail/open_addressing/open_addressing_ref_impl.cuh
Labels: type: bug, P0: Must have

#543 Fix a packed_cas build failure with libcudf
  include/cuco/detail/open_addressing/open_addressing_ref_impl.cuh
Labels: type: bug, helps: rapids, P0: Must have, Needs Review

#546 Fix `insert_or_apply` bug
  include/cuco/detail/static_map/static_map_ref.inl
  tests/static_map/insert_or_apply_test.cu
Labels: type: bug, topic: static_map, Needs Review

#552 Remove unified memory from test util
  tests/test_utils.cuh
  tests/test_utils.hpp
Labels: type: improvement

#553 use cudaDeviceGetAttribute to get sm count
  include/cuco/detail/utility/cuda.hpp
Labels: topic: performance, type: improvement

#549 Add experimental multimap insert and contains
  include/cuco/detail/static_multimap/static_multimap.inl
  include/cuco/detail/static_multimap/static_multimap_ref.inl
  include/cuco/static_multimap.cuh
  include/cuco/static_multimap_ref.cuh
  tests/CMakeLists.txt
  tests/static_multimap/insert_test.cu
Labels: Needs Review, topic: static_multimap, type: improvement

#557 Use `cuda::std::min` in a host device function
  include/cuco/detail/pair/helpers.cuh
Labels: type: improvement

#556 Fix while loop predicate
  include/cuco/detail/open_addressing/kernels.cuh
Labels: topic: performance, Needs Review, type: improvement

#559 Fix double hashing `with_hash_function`
  include/cuco/detail/open_addressing/open_addressing_ref_impl.cuh
  include/cuco/detail/probing_scheme/probing_scheme_base.cuh
  include/cuco/detail/probing_scheme/probing_scheme_impl.inl
  include/cuco/detail/static_multiset/static_multiset.inl
  include/cuco/detail/static_multiset/static_multiset_ref.inl
  include/cuco/detail/static_set/static_set_ref.inl
  include/cuco/pair.cuh
  include/cuco/probing_scheme.cuh
  include/cuco/static_multiset.cuh
  include/cuco/static_multiset_ref.cuh
  include/cuco/static_set_ref.cuh
  include/cuco/utility/traits.hpp
Labels: helps: rapids, Needs Review, type: improvement

#564 fix non-async overloads early return in `static_map`
  include/cuco/detail/static_map/static_map.inl
Labels: type: bug

#550 Add new dynamic_map host-bulk insert and contains
  include/cuco/detail/dynamic_map/dynamic_map.inl
  include/cuco/dynamic_map.cuh
  include/cuco/static_map.cuh
  tests/CMakeLists.txt
  tests/dynamic_map/unique_sequence_test_experimental.cu
Labels: Needs Review, topic: dynamic_map, type: improvement
