Repository NVIDIA/cuCollections, pull requests merged in 2024-06, with the labels that each got.

#496 Fix the `output_type` determination bug in OA find kernel
  include/cuco/detail/open_addressing/kernels.cuh
Labels: type: bug, helps: rapids, Needs Review

#497 Fix a typo in README.md
  README.md
Labels: type: docs

#494 Add multiset benchmarks
  benchmarks/CMakeLists.txt
  benchmarks/hash_table/static_multiset/contains_bench.cu
  benchmarks/hash_table/static_multiset/find_bench.cu
  benchmarks/hash_table/static_multiset/insert_bench.cu
Labels: type: feature request, Needs Review, topic: static_multiset

#504 Reset CUDA error after cudaFuncSetAttribute
  include/cuco/detail/hyperloglog/hyperloglog_ref.cuh
Labels: type: bug, P0: Must have, Needs Review

#503 Fix a build warning with ARM
  include/cuco/detail/static_map_kernels.cuh
Labels: type: improvement

#500 Add function for generating random byte strings with random lengths
  include/cuco/utility/key_generator.cuh
Labels: P2: Nice to have, Needs Review, type: improvement

#508 Add murmurhash3_x86_128 hash
  benchmarks/hash_bench.cu
  include/cuco/detail/hash_functions/murmurhash3.cuh
  include/cuco/detail/hash_functions/utils.cuh
  include/cuco/detail/hash_functions/xxhash.cuh
  include/cuco/hash_functions.cuh
  tests/utility/hash_test.cu
Labels: type: feature request, Needs Review

#511 Fix inconsistent use of noexcept
  include/cuco/aow_storage.cuh
  include/cuco/detail/distinct_count_estimator/distinct_count_estimator.inl
  include/cuco/detail/open_addressing/open_addressing_impl.cuh
  include/cuco/detail/static_map/static_map.inl
  include/cuco/detail/static_multiset/static_multiset.inl
  include/cuco/detail/static_set/static_set.inl
  include/cuco/detail/storage/aow_storage.inl
  include/cuco/distinct_count_estimator.cuh
  include/cuco/static_map.cuh
  include/cuco/static_multiset.cuh
  include/cuco/static_set.cuh
Labels: type: bug, helps: rapids, P0: Must have, Needs Review

#509 Add unit test for scalar vs. CGSize1 probing
  include/cuco/detail/extent/extent.inl
  include/cuco/detail/probing_scheme_impl.inl
  include/cuco/utility/fast_int.cuh
  tests/CMakeLists.txt
  tests/utility/probing_scheme_test.cu
Labels: Needs Review

#502 Bump rapids-cmake version
  CMakeLists.txt
  include/cuco/detail/hyperloglog/finalizer.cuh
  include/cuco/detail/open_addressing/functors.cuh
  include/cuco/detail/open_addressing/open_addressing_ref_impl.cuh
  include/cuco/detail/pair/traits.hpp
  include/cuco/pair.cuh
Labels: topic: build, type: improvement

#516 Add `static_multiset`
  benchmarks/CMakeLists.txt
  benchmarks/hash_table/static_multiset/contains_bench.cu
  benchmarks/hash_table/static_multiset/count_bench.cu
  benchmarks/hash_table/static_multiset/find_bench.cu
  benchmarks/hash_table/static_multiset/insert_bench.cu
  include/cuco/detail/equal_wrapper.cuh
  include/cuco/detail/open_addressing/kernels.cuh
  include/cuco/detail/open_addressing/open_addressing_impl.cuh
  include/cuco/detail/open_addressing/open_addressing_ref_impl.cuh
  include/cuco/detail/static_multiset/static_multiset.inl
  include/cuco/detail/static_multiset/static_multiset_ref.inl
  include/cuco/detail/utility/cuda.hpp
  include/cuco/operator.hpp
  include/cuco/static_multiset.cuh
  tests/CMakeLists.txt
  tests/static_multiset/contains_test.cu
  tests/static_multiset/count_test.cu
  tests/static_multiset/custom_count_test.cu
  tests/static_multiset/find_test.cu
Labels: type: feature request, topic: static_multiset

#512 Add benchmark evaluating hash function performance on random byte strings
  benchmarks/hash_bench.cu
Labels: topic: performance, P2: Nice to have, Needs Review

#506 Add static_multiset::for_each and its OA impl
  include/cuco/detail/open_addressing/open_addressing_ref_impl.cuh
  include/cuco/detail/static_multiset/static_multiset_ref.inl
  include/cuco/operator.hpp
  tests/CMakeLists.txt
  tests/static_multiset/for_each_test.cu
Labels: type: feature request, P1: Should have, Needs Review, topic: static_multiset

#522 Fix potential sync failure in find kernel
  include/cuco/detail/open_addressing/kernels.cuh
Labels: type: bug, Needs Review

#514 Add identity hasher
  include/cuco/detail/hash_functions/identity_hash.cuh
  include/cuco/hash_functions.cuh
  tests/utility/hash_test.cu
Labels: type: feature request, Needs Review

#523 [Review] Refactor hasher unit tests
  tests/utility/hash_test.cu
Labels: Needs Review, type: improvement
