Repository NVIDIA/cuCollections, pull requests merged in 2024-08, with the labels that each got.

#567 Fix a dangling reference warning with GCC-13
  include/cuco/detail/open_addressing/functors.cuh
Labels: type: bug, Needs Review

#569 Make legacy multimap thread safe
  include/cuco/detail/static_multimap/static_multimap.inl
  include/cuco/static_multimap.cuh
Labels: type: bug, Needs Review, topic: static_multimap

#551 Add host-bulk `insert_or_apply` using shared_memory
  include/cuco/detail/static_map/kernels.cuh
  include/cuco/detail/static_map/static_map.inl
  include/cuco/detail/static_map/static_map_ref.inl
  tests/static_map/insert_or_apply_test.cu
Labels: topic: static_map, topic: performance, Needs Review, type: improvement

#570 Add multimap conditional contains
  include/cuco/detail/static_multimap/static_multimap.inl
  include/cuco/static_multimap.cuh
  tests/CMakeLists.txt
  tests/static_multimap/insert_contains_test.cu
Labels: type: feature request, topic: static_multimap

#555 Add `init` element overload to `insert_or_apply`
  benchmarks/static_map/insert_or_apply_bench.cu
  include/cuco/detail/static_map/helpers.cuh
  include/cuco/detail/static_map/kernels.cuh
  include/cuco/detail/static_map/static_map.inl
  include/cuco/detail/static_map/static_map_ref.inl
  include/cuco/operator.hpp
  include/cuco/static_map.cuh
  include/cuco/utility/reduction_functors.cuh
  tests/static_map/insert_or_apply_test.cu
Labels: type: feature request, topic: static_map, Needs Review

#572 Expose `storage_ref` and `probing_scheme` in all container refs
  include/cuco/detail/static_map/static_map_ref.inl
  include/cuco/detail/static_multimap/static_multimap_ref.inl
  include/cuco/detail/static_multiset/static_multiset_ref.inl
  include/cuco/detail/static_set/static_set_ref.inl
  include/cuco/static_map_ref.cuh
  include/cuco/static_multimap_ref.cuh
  include/cuco/static_multiset_ref.cuh
  include/cuco/static_set_ref.cuh
Labels: type: feature request, helps: rapids, Needs Review

#575 Bump to RAPIDS 24.10
  .devcontainer/cuda11.8-gcc11/devcontainer.json
  .devcontainer/cuda12.5-gcc12/devcontainer.json
  .devcontainer/cuda12.5-gcc13/devcontainer.json
  .devcontainer/devcontainer.json
  CMakeLists.txt
  ci/matrix.yml
Labels: topic: build, topic: CI, type: improvement

#574 Fix `ProbeKey` description in the documentation
  include/cuco/detail/open_addressing/open_addressing_ref_impl.cuh
  include/cuco/detail/static_map/static_map_ref.inl
  include/cuco/detail/static_multimap/static_multimap_ref.inl
  include/cuco/detail/static_multiset/static_multiset_ref.inl
  include/cuco/detail/static_set/static_set_ref.inl
Labels: type: docs

#565 Add host-bulk `for_each` for static_map
  include/cuco/detail/open_addressing/kernels.cuh
  include/cuco/detail/open_addressing/open_addressing_impl.cuh
  include/cuco/detail/open_addressing/open_addressing_ref_impl.cuh
  include/cuco/detail/static_map/static_map.inl
  include/cuco/detail/static_map/static_map_ref.inl
  include/cuco/static_map.cuh
  tests/CMakeLists.txt
  tests/static_map/for_each_test.cu
  tests/static_multiset/for_each_test.cu
Labels: type: feature request, topic: static_map, Needs Review

#578 Enable Initialization for Empty Storage
  include/cuco/detail/storage/aow_storage.inl
  tests/utility/storage_test.cu
Labels: helps: rapids, type: improvement

#579 Fix `insert_or_apply`
  include/cuco/detail/static_map/kernels.cuh
  include/cuco/detail/static_map/static_map.inl
  include/cuco/static_map.cuh
Labels: type: bug

#580 Fix retrieve_all for containers with large capacity
  include/cuco/detail/open_addressing/open_addressing_impl.cuh
  tests/static_set/large_input_test.cu
Labels: type: bug, helps: rapids, Needs Review

#583 Improve the probing scheme header
  include/cuco/detail/utils.cuh
  include/cuco/probing_scheme.cuh
Labels: Needs Review, type: improvement

#584 Expose `key_eq` member accessors
  include/cuco/detail/static_map/static_map.inl
  include/cuco/detail/static_multimap/static_multimap.inl
  include/cuco/detail/static_multiset/static_multiset.inl
  include/cuco/detail/static_set/static_set.inl
  include/cuco/static_map.cuh
  include/cuco/static_multimap.cuh
  include/cuco/static_multiset.cuh
  include/cuco/static_set.cuh
Labels: type: feature request, Needs Review

#571 Add multimap count and conditional insert
  include/cuco/detail/open_addressing/open_addressing_impl.cuh
  include/cuco/detail/static_multimap/static_multimap.inl
  include/cuco/detail/static_multimap/static_multimap_ref.inl
  include/cuco/detail/static_multiset/static_multiset.inl
  include/cuco/static_map.cuh
  include/cuco/static_multimap.cuh
  include/cuco/static_multimap_ref.cuh
  include/cuco/static_multiset.cuh
  tests/CMakeLists.txt
  tests/static_multimap/count_test.cu
  tests/static_multimap/insert_if_test.cu
Labels: type: feature request, Needs Review, topic: static_multimap

#587 Expose hash_function member function
  include/cuco/detail/open_addressing/open_addressing_impl.cuh
  include/cuco/detail/open_addressing/open_addressing_ref_impl.cuh
  include/cuco/detail/probing_scheme/probing_scheme_impl.inl
  include/cuco/detail/static_map/static_map.inl
  include/cuco/detail/static_map/static_map_ref.inl
  include/cuco/detail/static_multimap/static_multimap.inl
  include/cuco/detail/static_multimap/static_multimap_ref.inl
  include/cuco/detail/static_multiset/static_multiset.inl
  include/cuco/detail/static_multiset/static_multiset_ref.inl
  include/cuco/detail/static_set/static_set.inl
  include/cuco/detail/static_set/static_set_ref.inl
  include/cuco/probing_scheme.cuh
  include/cuco/static_map.cuh
  include/cuco/static_map_ref.cuh
  include/cuco/static_multimap.cuh
  include/cuco/static_multimap_ref.cuh
  include/cuco/static_multiset.cuh
  include/cuco/static_multiset_ref.cuh
  include/cuco/static_set.cuh
  include/cuco/static_set_ref.cuh
Labels: type: feature request, Needs Review

#591 Add diagnostic to detect unsupported or missing CCCL
  include/cuco/detail/__config
Labels: topic: build, P2: Nice to have, Needs Review, type: improvement

#595 Disable `--expt-relaxed-constexpr` with CCCL enhancements
  benchmarks/CMakeLists.txt
  benchmarks/hash_function/hash_function_bench.cu
  examples/CMakeLists.txt
  examples/static_set/device_subsets_example.cu
  include/cuco/detail/__config
  include/cuco/detail/hash_functions/murmurhash3.cuh
  include/cuco/detail/hash_functions/utils.cuh
  include/cuco/detail/hash_functions/xxhash.cuh
  include/cuco/detail/hyperloglog/hyperloglog_ref.cuh
  include/cuco/detail/open_addressing/open_addressing_ref_impl.cuh
  include/cuco/detail/probe_sequence_impl.cuh
  include/cuco/static_multimap.cuh
  include/cuco/utility/key_generator.cuh
  tests/CMakeLists.txt
  tests/static_map/custom_type_test.cu
  tests/static_multimap/custom_type_test.cu
  tests/utility/hash_test.cu
Labels: type: improvement
