Repository NVIDIA/cuCollections, pull requests merged in 2025-02, with the labels that each got.

#665 Add find APIs for map with custom hash and key equality functions
  include/cuco/detail/static_map/static_map.inl
  include/cuco/static_map.cuh
  tests/static_map/find_test.cu
Labels: type: feature request, topic: static_map, Needs Review

#667 Replace the deprecated thrust::identity with cuda::std::identity
  include/cuco/detail/bloom_filter/bloom_filter_impl.cuh
  include/cuco/detail/hash_functions/identity_hash.cuh
  include/cuco/detail/open_addressing/open_addressing_impl.cuh
  include/cuco/detail/open_addressing/open_addressing_ref_impl.cuh
Labels: type: improvement

#668 Get rid of the deprecated `thrust::identity` for tests and examples
  README.md
  examples/static_set/device_ref_example.cu
  examples/static_set/host_bulk_example.cu
  tests/bloom_filter/unique_sequence_test.cu
  tests/dynamic_map/erase_test.cu
  tests/dynamic_map/unique_sequence_test.cu
  tests/dynamic_map/unique_sequence_test_experimental.cu
  tests/static_map/contains_test.cu
  tests/static_map/custom_type_test.cu
  tests/static_map/duplicate_keys_test.cu
  tests/static_map/erase_test.cu
  tests/static_map/hash_test.cu
  tests/static_map/heterogeneous_lookup_test.cu
  tests/static_map/insert_and_find_test.cu
  tests/static_map/shared_memory_test.cu
  tests/static_map/stream_test.cu
  tests/static_multimap/heterogeneous_lookup_test.cu
  tests/static_multimap/insert_contains_test.cu
  tests/static_multiset/contains_test.cu
  tests/static_set/heterogeneous_lookup_test.cu
  tests/static_set/insert_and_find_test.cu
  tests/static_set/large_input_test.cu
  tests/static_set/shared_memory_test.cu
  tests/static_set/unique_sequence_test.cu
  tests/utility/hash_test.cu
Labels: Needs Review, type: improvement

#670 Bloom filter optimizations (2/5): Eliminate lmem access during salt lookup in arrow policy
  include/cuco/detail/bloom_filter/arrow_filter_policy.cuh
Labels: helps: rapids, topic: performance, topic: bloom_filter

#671 Bloom filter optimizations (3/5): Avoid error handling through __trap
  include/cuco/detail/bloom_filter/default_filter_policy_impl.cuh
Labels: P1: Should have, type: improvement, topic: bloom_filter

#672 Bloom filter optimizations (4/5): Implement device bulk add
  benchmarks/bloom_filter/add_bench.cu
  benchmarks/bloom_filter/contains_bench.cu
  include/cuco/bloom_filter_ref.cuh
  include/cuco/detail/bloom_filter/bloom_filter_impl.cuh
  include/cuco/detail/bloom_filter/bloom_filter_ref.inl
  include/cuco/detail/bloom_filter/kernels.cuh
Labels: helps: rapids, topic: performance, type: improvement, topic: bloom_filter

#675 [REVIEW] fixed a minor index issue in bloom_filter_impl
  include/cuco/detail/bloom_filter/bloom_filter_impl.cuh
Labels: type: bug, topic: bloom_filter

#677 Update examples to use tranform iterator for insert instead of zip
  README.md
  examples/static_map/host_bulk_example.cu
Labels: Needs Review, type: improvement

#678 Add lazy_discard_iterator benchmark utility
  benchmarks/benchmark_utils.hpp
Labels: P2: Nice to have

#679 Get rid of the deprecated aow alias
  README.md
  examples/static_set/device_subsets_example.cu
  include/cuco/bucket_storage.cuh
  tests/static_map/shared_memory_test.cu
  tests/static_set/shared_memory_test.cu
  tests/utility/storage_test.cu
Labels: type: improvement

#680 Update return type from const& to value in detail APIs
  include/cuco/detail/open_addressing/open_addressing_ref_impl.cuh
  include/cuco/detail/static_map/static_map_ref.inl
Labels: Needs Review, type: improvement

#684 Fix function visibility in bloom_filter_impl
  include/cuco/detail/bloom_filter/bloom_filter_impl.cuh
Labels: type: bug, topic: bloom_filter

#687 Fix typos identified by cursor
  include/cuco/detail/open_addressing/open_addressing_impl.cuh
  include/cuco/detail/open_addressing/open_addressing_ref_impl.cuh
  include/cuco/static_map.cuh
  include/cuco/static_map_ref.cuh
  include/cuco/static_multimap.cuh
  include/cuco/static_multimap_ref.cuh
  include/cuco/static_multiset.cuh
  include/cuco/static_set.cuh
  include/cuco/static_set_ref.cuh
Labels: type: docs, type: improvement
