Repository NVIDIA/cuCollections, pull requests merged in 2025-04, with the labels that each got.

#699 Fix a copy-paste leftover in the doc
  include/cuco/static_multimap.cuh
Labels: type: docs

#700 Replace deprecated thrust features
  README.md
  examples/static_map/count_by_key_example.cu
  examples/static_map/device_ref_example.cu
  examples/static_set/device_subsets_example.cu
  examples/static_set/shared_memory_example.cu
  include/cuco/detail/open_addressing/open_addressing_ref_impl.cuh
  include/cuco/detail/static_map/static_map_ref.inl
  include/cuco/dynamic_map.cuh
  include/cuco/static_map.cuh
  include/cuco/static_multimap.cuh
  include/cuco/static_multiset.cuh
  include/cuco/static_set.cuh
  include/cuco/utility/key_generator.cuh
  tests/hyperloglog/spark_parity_test.cu
  tests/static_map/capacity_test.cu
  tests/static_map/contains_test.cu
  tests/static_map/duplicate_keys_test.cu
  tests/static_map/erase_test.cu
  tests/static_map/find_test.cu
  tests/static_map/for_each_test.cu
  tests/static_map/hash_test.cu
  tests/static_map/insert_and_find_test.cu
  tests/static_map/insert_or_apply_test.cu
  tests/static_map/insert_or_assign_test.cu
  tests/static_map/retrieve_test.cu
  tests/static_map/shared_memory_test.cu
  tests/static_multimap/count_test.cu
  tests/static_multimap/find_test.cu
  tests/static_multimap/insert_contains_test.cu
  tests/static_multimap/insert_if_test.cu
  tests/static_multimap/multiplicity_test.cu
  tests/static_multimap/retrieve_test.cu
  tests/static_multiset/large_input_test.cu
  tests/static_multiset/retrieve_test.cu
  tests/static_set/capacity_test.cu
  tests/static_set/for_each_test.cu
  tests/static_set/insert_and_find_test.cu
  tests/static_set/large_input_test.cu
  tests/static_set/retrieve_all_test.cu
  tests/static_set/retrieve_test.cu
  tests/static_set/shared_memory_test.cu
  tests/utility/probing_scheme_test.cu
Labels: helps: rapids, type: improvement

#702 Use relaxed memory-order in dynamic_map::find
  include/cuco/detail/dynamic_map_kernels.cuh
Labels: topic: dynamic_map, type: improvement
