Repository NVIDIA/cuCollections, pull requests merged in 2025-05, with the labels that each got.

#708 Update cuco implementations to use cuda::std utilities when appropriate
  include/cuco/detail/bloom_filter/bloom_filter_impl.cuh
  include/cuco/detail/bloom_filter/kernels.cuh
  include/cuco/detail/open_addressing/functors.cuh
  include/cuco/detail/open_addressing/kernels.cuh
  include/cuco/detail/open_addressing/open_addressing_impl.cuh
  include/cuco/detail/open_addressing/open_addressing_ref_impl.cuh
  include/cuco/detail/pair/helpers.cuh
  include/cuco/detail/pair/pair.inl
  include/cuco/detail/pair/tuple_helpers.inl
  include/cuco/detail/static_map.inl
  include/cuco/detail/static_map/kernels.cuh
  include/cuco/detail/static_map/static_map.inl
  include/cuco/detail/static_map/static_map_ref.inl
  include/cuco/detail/static_multimap/device_view_impl.inl
  include/cuco/detail/static_multimap/kernels.cuh
  include/cuco/detail/static_multimap/static_multimap.inl
  include/cuco/detail/static_multiset/static_multiset_ref.inl
  include/cuco/detail/static_set/static_set_ref.inl
  include/cuco/detail/utils.cuh
  include/cuco/dynamic_map.cuh
  include/cuco/operator.hpp
  include/cuco/pair.cuh
  include/cuco/static_map.cuh
  include/cuco/utility/key_generator.cuh
  include/cuco/utility/traits.hpp
Labels: type: improvement

#705 Upgrade rapids-cmake version to fetch CCCL-2.8
  CMakeLists.txt
Labels: topic: build

#712 Remove constexpr from the HLL finalizer to resolve a build error with CCCL 3.0
  include/cuco/detail/hyperloglog/finalizer.cuh
  include/cuco/detail/hyperloglog/hyperloglog_impl.cuh
Labels: type: bug, topic: hyperloglog

#709 Add retrieve_all for dynamic_map
  benchmarks/CMakeLists.txt
  benchmarks/dynamic_map/retrieve_all_bench.cu
  include/cuco/detail/dynamic_map.inl
  include/cuco/detail/dynamic_map_kernels.cuh
  include/cuco/dynamic_map.cuh
  tests/CMakeLists.txt
  tests/dynamic_map/retrieve_all_test.cu
Labels: type: feature request, Needs Review, topic: dynamic_map

#715 Update CMake to fetch the nvbench version used in rapids-cmake
  CMakeLists.txt
  benchmarks/CMakeLists.txt
Labels: topic: build, Needs Review

#706 Add atomic storage test
  tests/CMakeLists.txt
  tests/static_set/atomic_storage_test.cu
Labels: helps: rapids, Needs Review, type: improvement

#710 Use `cuda::std::tuple` to replace `thrust::tuple`
  README.md
  examples/static_map/device_ref_example.cu
  include/cuco/detail/open_addressing/functors.cuh
  include/cuco/detail/static_map.inl
  include/cuco/detail/static_map/static_map.inl
  include/cuco/detail/static_multimap/device_view_impl.inl
  include/cuco/detail/static_multimap/static_multimap.inl
  include/cuco/detail/utils.cuh
  include/cuco/utility/key_generator.cuh
  tests/dynamic_map/erase_test.cu
  tests/dynamic_map/unique_sequence_test.cu
  tests/dynamic_map/unique_sequence_test_experimental.cu
  tests/static_map/contains_test.cu
  tests/static_map/find_test.cu
  tests/static_map/for_each_test.cu
  tests/static_map/insert_or_apply_test.cu
  tests/static_map/shared_memory_test.cu
  tests/static_map/stream_test.cu
  tests/static_multimap/find_test.cu
  tests/static_multimap/insert_contains_test.cu
  tests/static_multiset/contains_test.cu
  tests/static_multiset/find_test.cu
  tests/static_set/for_each_test.cu
  tests/static_set/shared_memory_test.cu
  tests/static_set/unique_sequence_test.cu
Labels: type: feature request, Needs Review

#707 Update RAPIDS, CUDA versions
  .devcontainer/cuda11.8-gcc11/devcontainer.json
  .devcontainer/cuda12.8-gcc12/devcontainer.json
  .devcontainer/cuda12.8-gcc13/devcontainer.json
  .devcontainer/devcontainer.json
  ci/matrix.yml
  ci/update_rapids_version.sh
Labels: topic: CI, type: improvement

#718 Update pre-commit clang-format version to 20.1.4
  .pre-commit-config.yaml
  tests/bloom_filter/arrow_policy_test.cu
Labels: topic: CI

#717 Add host-bulk `count_each` for multiset
  include/cuco/detail/open_addressing/kernels.cuh
  include/cuco/detail/open_addressing/open_addressing_impl.cuh
  include/cuco/detail/static_multiset/static_multiset.inl
  include/cuco/static_multiset.cuh
  tests/static_multiset/count_test.cu
Labels: type: feature request, helps: rapids, Needs Review, topic: static_multiset

#719 Add proper handling for invalid desired load factor
  include/cuco/detail/extent/extent.inl
  include/cuco/detail/open_addressing/open_addressing_impl.cuh
  include/cuco/extent.cuh
  tests/CMakeLists.txt
  tests/static_multiset/load_factor_test.cu
  tests/test_utils.hpp
  tests/utility/extent_test.cu
Labels: type: bug, helps: rapids, Needs Review
